image:
  name: atlassian/default-image:2

release-dev: &release-dev
  step:
    name: Release development version
    image: python:3.7
    script:
      - set -ex
      - pip install semversioner
      - VERSION=$(semversioner current-version)
      - IMAGE=bitbucketpipelines/$BITBUCKET_REPO_SLUG
      - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - docker build -t ${IMAGE} .
      - docker tag ${IMAGE} ${IMAGE}:${VERSION}-dev
      - docker push ${IMAGE}:${VERSION}-dev
    services:
      - docker
    caches:
      - pip

test: &test
  step:
    name: Test
    image: bitbucketpipelines/aws-elasticbeanstalk-deploy-test-step:latest
    script:
      - export DOCKERHUB_IMAGE="bitbucketpipelines/${BITBUCKET_REPO_SLUG}"
      - export DOCKERHUB_TAG=${BITBUCKET_BUILD_NUMBER}
      - pip install -r test/requirements.txt
      - pytest --verbose test/test.py  --junitxml=test-reports/report.xml
    services:
      - docker
    caches:
      - pip

push: &push
  step:
    name: Push and Tag
    script:
      - pipe: docker://bitbucketpipelines/meta-pipe:0.0.2
        variables:
          DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
          DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
          IMAGE: bitbucketpipelines/${BITBUCKET_REPO_SLUG}

pipelines:
    default:
    - <<: *test
    - <<: *release-dev
    branches:
        master:
        - <<: *test
        - <<: *push

