image:
  name: atlassian/default-image:2


setup: &setup
  step:
    name: Setup tesging resources
    script:
      - STACK_NAME="bbci-pipes-test-infrastructure-ebs-nodejs-del-${BITBUCKET_BUILD_NUMBER}"
      - EBS_APP_NAME="bbci-pipes-test-infrastructure-${BITBUCKET_BUILD_NUMBER}"
      - pipe: atlassian/aws-cloudformation-deploy:0.5.0
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          STACK_NAME: ${STACK_NAME}
          TEMPLATE: "./test/CloudFormationStackTemplate_nodejs.yml"
          CAPABILITIES: ['CAPABILITY_IAM']
          WAIT: 'true'
          STACK_PARAMETERS: >
              [{
                "ParameterKey": "ApplicationName",
                "ParameterValue": "${EBS_APP_NAME}"
              }]


release-dev: &release-dev
  step:
    name: Release development version
    image: python:3.7
    script:
      - set -ex
      - pip install semversioner
      - VERSION=$(semversioner current-version)
      - IMAGE=bitbucketpipelines/$BITBUCKET_REPO_SLUG
      - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - docker build -t ${IMAGE} .
      - docker tag ${IMAGE} ${IMAGE}:${VERSION}-dev
      - docker push ${IMAGE}:${VERSION}-dev
    services:
      - docker
    caches:
      - pip


test: &test
  step:
    name: Test
    image: bitbucketpipelines/aws-elasticbeanstalk-deploy-test-step:latest
    script:
      - export DOCKERHUB_IMAGE="bitbucketpipelines/${BITBUCKET_REPO_SLUG}"
      - export DOCKERHUB_TAG=${BITBUCKET_BUILD_NUMBER}
      - pip install -r test/requirements.txt
      - pytest --verbose test/test.py  --junitxml=test-reports/report.xml
    after-script:
      - STACK_NAME="bbci-pipes-test-infrastructure-ebs-nodejs-del-${BITBUCKET_BUILD_NUMBER}"
      - pip install awscli
      - aws cloudformation delete-stack --stack-name ${STACK_NAME}
    services:
      - docker
    caches:
      - pip


push: &push
  step:
    name: Push and Tag
    script:
      - pipe: docker://bitbucketpipelines/meta-pipe:0.0.2
        variables:
          DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
          DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
          IMAGE: bitbucketpipelines/${BITBUCKET_REPO_SLUG}


pipelines:
    default:
    - <<: *setup
    - <<: *test
    - <<: *release-dev
    branches:
        master:
        - <<: *setup
        - <<: *test
        - <<: *push

